[build]
  command = "gatsby build"
  functions = "functions"
  publish = "public/"

[[redirects]]
 from = "https://about-leverpress-umich-gitlab.netlify.com/*"
 to = "https://www.leverpress.org/:splat"
 status = 301

[[redirects]]
 from = "/libraries"
 to = "/join"
 status = 301

[[redirects]]
 from = "/contact"
 to = "/"
 status = 301

[[redirects]]
 from = "/governance"
 to = "/about"
 status = 301

[[redirects]]
 from = "/history"
 to = "/about"
 status = 301

[[redirects]]
 from = "/consortium"
 to = "/about"
 status = 301

[[redirects]]
 from = "/our-values-and-commitments"
 to = "/about"
 status = 301