[build]
  command = "gatsby build"
  functions = "functions"
  publish = "public/"

[[redirects]]
 from = "https://about-leverpress-umich-gitlab.netlify.com/*"
 to = "https://www.leverpress.org/:splat"
 status = 301

[[redirects]]
 from = "/libraries"
 to = "/join"
 status = 301

[[redirects]]
 from = "/contact"
 to = "/"
 status = 301

[[redirects]]
 from = "/governance"
 to = "/about"
 status = 301

[[redirects]]
 from = "/history"
 to = "/about"
 status = 301

[[redirects]]
 from = "/consortium"
 to = "/about"
 status = 301

[[redirects]]
 from = "/our-values-and-commitments"
 to = "/about"
 status = 301

[[redirects]]
from = "/2019/09/20/from-the-director-of-lever-press/"
to = "/news/2019-09-27-from-the-director/"
status = 301

[[redirects]]
 from = "/2019/09/20/new-faces-at-lever/"
 to = "/news/2020-01-15-new-faces-at-lever/"
 status = 301

[[redirects]]
 from = "/2019/09/20/update-from-the-lever-press-annual-meeting/"
 to = "/news/2019-09-24-update-from-the-lever-press-annual-meeting/"
 status = 301

[[redirects]]
 from = "/2018/*"
 to = "/news"
 status = 301

[[redirects]]
 from = "/2017/*"
 to = "/news"
 status = 301

[[redirects]]
 from = "/2016/*"
 to = "/news"
 status = 301

[[redirects]]
 from= "/wp-content/uploads/2019/10/LeverPress-Catalog-web.pdf"
 to = "/assets/LeverPress-Fall19-Spring20.pdf"
 status = 301

 