backend:
  name: gitlab
  repo: michigan-publishing/about-leverpress
  auth_type: implicit
  app_id: 3b36ad4e69326d2ddc0a722be68ce1aa60ed5d006deb6d7dc7e4281032b54a49
  api_root: https://gitlab.umich.edu/api/v4
  base_url: https://gitlab.umich.edu
  auth_endpoint: oauth/authorize
media_folder: static/assets
public_folder: assets
collections:
  - name: news
    label: News
    folder: src/content/news
    create: true
    slug: "news/{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: templateKey, label: "Template Key", widget: hidden, default: news }
      - { name: title, label: Title }
      - { name: date, label: Published, widget: datetime }
      - { name: image, label: Image, widget: image }
      - { name: body, label: Body, widget: markdown }
  - name: events
    label: Events
    folder: src/content/events
    create: true
    slug: "events/{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: templateKey, label: "Template Key", widget: hidden, default: event }
      - { name: title, label: Title }
      - { name: date, label: Published, widget: datetime }
      - { name: image, label: Image, widget: image }
      - { name: body, label: Body, widget: markdown }
  - name: books
    label: Books
    folder: src/content/books
    create: true
    slug: "books/{{authorLastname}}-{{title}}"
    fields:
      - { name: templateKey, label: "Template Key", widget: hidden, default: book }
      - { name: title, label: Title }
      - { name: authorLastname, label: "Primary Author Last Name" }
      - { name: author, label: "Author(s)" }
      - { name: cover, label: Cover, widget: image }
      - { name: description, label: Description }
      - { name: orderOnPage, label: "Order on Front Page", widget: number }
      - { name: readLink, label: "Read Link" }
      - { name: buyLink, label: "Buy Link" }
  - name: pages
    label: Pages
    files:
      - file: "src/content/pages/about.md"
        name: about
        label: About
        fields:
          - { name: templateKey, label: "Template Key", widget: hidden, default: about-page }
          - { name: path, label: Path, widget: hidden, default: "/about" }
          - { name: title, label: About }
          - { name: body, label: Body, widget: markdown }
      - file: "src/content/pages/info.md"
        name: info
        label: Info
        fields:
          - { name: templateKey, label: "Template Key", widget: hidden, default: info-page }
          - { name: path, label: Path, widget: hidden, default: "/info" }
          - { name: title, label: Info }
          - { name: body, label: Body, widget: markdown }
      - file: "src/content/pages/impact.md"
        name: impact
        label: Impact
        fields:
          - { name: templateKey, label: "Template Key", widget: hidden, default: impact-page }
          - { name: path, label: Path, widget: hidden, default: "/impact" }
          - { name: title, label: Impact }
          - { name: readershipMapDescription, label: "Readership Map Description", widget: markdown }
          - { name: googleDataStudioDescription, label: "Google Data Studio Description", widget: markdown }
